-- LIST OF SQL QUERIES RUN TO CREATE THE STRUCTURE OF THE SQL SERVER DATABASE
--   'PizzaLocationDB' USED FOR PROJECT_1.
-------> ALL QUERIES COMMENTED OUT AFTER BEING RUN SUCCESSFULLY TO AVOID
--       ANNOYING ERROR HIGHLIGHTING ETC...


-- CREATE SCHEMA PizzaLocation;

-- CREATE TABLE tbl_Orders
-- (
--     OrderID INT PRIMARY KEY,
--     CustomerID INT NOT NULL,
--     OrderLocation NVARCHAR(50) NOT NULL,
--     OrderTime DATETIME2,
--     OrderCost DECIMAL(19, 4) NOT NULL
-- )

ALTER TABLE tbl_Orders
ADD LocationID INT;

CREATE TABLE tbl_Location
(

)